insert into Diagnosis (diagnosis_id, diagnosis_name) values (1, 'Coffea arabica L.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (2, 'Acer negundo L. var. interius (Britton) Sarg.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (3, 'Hulsea vestita A. Gray ssp. gabrielensis Wilken');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (4, 'Sterculia apetala (Jacq.) Karst.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (5, 'Astragalus gracilis Nutt.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (6, 'Madia elegans D. Don ex Lindl. ssp. wheeleri (A. Gray) D.D. Keck');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (7, 'Peltula euploca (Ach.) Poelt');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (8, 'Facelis retusa (Lam.) Sch. Bip.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (9, 'Platanthera ×bicolor (Raf.) Luer (pro sp.)');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (10, 'Brachythecium reflexum (Starke) Schimp. var. pacificum Renauld & Cardot');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (11, 'Herniaria incana Lam.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (12, 'Sclerocactus parviflorus Clover & Jotter ssp. terrae-canyonae');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (13, 'Pritchardia Seem. & H. Wendl.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (14, 'Zahlbrucknerella californica Henssen');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (15, 'Primula incana M.E. Jones');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (16, 'Phyllostachys Siebold & Zucc.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (17, 'Carex ×firmior (Norman) Holmb.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (18, 'Sphagnum strictum Sull.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (19, 'Acanthocereus (Engelm. ex A. Berger) Britton & Rose');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (20, 'Erica canaliculata Andrews');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (21, 'Vernonia noveboracensis (L.) Michx.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (22, 'Isoetes texana Singhurst, Rushing & W.C. Holmes');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (23, 'Wikstroemia uva-ursi A. Gray');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (24, 'Chaenactis suffrutescens A. Gray');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (25, 'Packera bolanderi (A. Gray) W.A. Weber & Á. Löve');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (26, 'Schiedea helleri Sherff');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (27, 'Caloplaca trachyphylla (Tuck.) Zahlbr.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (28, 'Byssoloma Trevis.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (29, 'Caloplaca saxifragarum Poelt');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (30, 'Melaspilea demissa (Tuck.) Zahlbr.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (31, 'Penstemon leiophyllus Pennell var. francisci-pennellii (Crosswh.) N.H. Holmgren');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (32, 'Physocarpus monogynus (Torr.) J.M. Coult.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (33, 'Corispermum americanum (Nutt.) Nutt.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (34, 'Psychotria pubescens Sw.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (35, 'Asclepias pedicellata Walter');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (36, 'Lamium L.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (37, 'Astragalus hallii A. Gray var. fallax (M.E. Jones) Barneby');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (38, 'Arctostaphylos glandulosa Eastw.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (39, 'Tradescantia leiandra Torr. var. leiandra');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (40, 'Salvia davidsonii Greenm.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (41, 'Polygonum segetum Kunth');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (42, 'Mabrya Elisens');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (43, 'Picrothamnus desertorum Nutt.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (44, 'Alocasia macrorrhizos (L.) G. Don');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (45, 'Drosera L.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (46, 'Mabrya acerifolia (Pennell) Elisens');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (47, 'Pholisma arenarium Nutt. ex Hook.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (48, 'Thelocarpon superellum Nyl.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (49, 'Peltandra Raf.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (50, 'Chaenactis suffrutescens A. Gray');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (51, 'Scirpus pallidus (Britton) Fernald');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (52, 'Delphinium decorum Fisch. & C.A. Mey.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (53, 'Uncinia hamata (Sw.) Urb.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (54, 'Nymphoides cristata (Roxb.) Kuntze');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (55, 'Aesculus parviflora Walter');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (56, 'Colubrina arborescens (Mill.) Sarg.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (57, 'Pogogyne douglasii Benth. ssp. douglasii');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (58, 'Geranium kauaiense (Rock) H. St. John');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (59, 'Sisyrinchium elmeri Greene');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (60, 'Ulmus crassifolia Nutt.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (61, 'Phyllostachys rubromarginata McClure');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (62, 'Neofuscelia ahtii (Essl.) Essl.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (63, 'Psychotria nervosa Sw.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (64, 'Astragalus bolanderi A. Gray');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (65, 'Collema fragrans (Sm.) Ach.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (66, 'Astrothelium versicolor Müll. Arg.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (67, 'Allium crispum Greene');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (68, 'Chamaesyce porteriana Small var. porteriana');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (69, 'Nemophila pulchella Eastw. var. pulchella');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (70, 'Eleutheranthera ruderalis (Sw.) Sch. Bip.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (71, 'Centaurium venustum (A. Gray) B.L. Rob.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (72, 'Centaurea diluta Aiton');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (73, 'Cleome ornithopodioides L., nom. inq.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (74, 'Monolopia lanceolata Nutt.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (75, 'Bobea Gaudich.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (76, 'Penstemon cardinalis Wooton & Standl.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (77, 'Physcia pseudospeciosa J.W. Thomson');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (78, 'Leucothoe axillaris (Lam.) D. Don');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (79, 'Lotus oblongifolius (Benth.) Greene');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (80, 'Lepidium ramosissimum A. Nelson var. ramosissimum');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (81, 'Anemia wrightii Baker');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (82, 'Pharus L.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (83, 'Helianthus praecox Engelm. & A. Gray ssp. praecox');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (84, 'Rubus linkianus Ser.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (85, 'Glandularia maritima (Small) Small');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (86, 'Licaria brittoniana Allen & Gregory');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (87, 'Fremontodendron mexicanum Davidson');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (88, 'Mitella caulescens Nutt.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (89, 'Ceanothus papillosus Torr. & A. Gray');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (90, 'Allium chinense G. Don');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (91, 'Ranunculus uncinatus D. Don ex G. Don var. parviflorus (Torr.) L.D. Benson');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (92, 'Ericameria linearifolia (DC.) Urbatsch & Wussow');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (93, 'Allium monticola Davidson');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (94, 'Cheirodendron trigynum (Gaudich.) A. Heller');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (95, 'Physaria rectipes (Wooton & Standl) O''Kane & Al-Shehbaz');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (96, 'Agrostis microphylla Steud.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (97, 'Leiophyllum buxifolium (Bergius) Elliott');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (98, 'Dysodiopsis (A. Gray) Rydb.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (99, 'Cirsium hillii (Canby) Fernald');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (100, 'Ceratostigma willmottianum Stapf');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (101, '×Agropogon littoralis (Sm.) C.E. Hubbard');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (102, 'Yucca thompsoniana Trel.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (103, 'Ceanothus greggii A. Gray var. perplexans (Trel.) Jeps.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (104, 'Eugenia koolauensis O. Deg.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (105, 'Rhamnus arguta Maxim. var. velutina Hand.-Maz.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (106, 'Gynura aurantiaca (Blume) DC.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (107, 'Allium scorodoprasum L. ssp. rotundum (L.) Stearn');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (108, 'Lonchocarpus domingensis (Turp. ex Pers.) DC.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (109, 'Limnanthes gracilis Howell ssp. parishii (Jeps.) R.M. Beauch.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (110, 'Kalmia angustifolia L.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (111, 'Warnstorfia procera (Renauld & Arnell) Tuom. & T. Kop.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (112, 'Sphinctrina turbinata (Pers. ex Fr.) De Not.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (113, 'Echinacea laevigata (C.L. Boynt. & Beadle) S.F. Blake');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (114, 'Viola ×wittrockiana Gams.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (115, 'Draba cusickii B.L. Rob. ex O.E. Schulz var. cusickii');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (116, 'Hylocereus costaricensis (F.A.C. Weber) Britton & Rose');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (117, 'Ceanothus thyrsiflorus Eschsch.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (118, 'Menodora longiflora A. Gray');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (119, 'Cotoneaster adpressus Bois');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (120, 'Paxistima canbyi A. Gray');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (121, 'Castanea pumila (L.) Mill. var. ozarkensis (Ashe) Tucker');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (122, 'Pentachaeta alsinoides Greene');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (123, 'Astragalus zionis M.E. Jones var. zionis');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (124, 'Orobanche uniflora L.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (125, 'Cyrtandra crenata H. St. John & Storey');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (126, 'Fendlera wrightii (A. Gray) A. Heller');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (127, 'Lepidium campestre (L.) W.T. Aiton');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (128, 'Glossopetalon spinescens A. Gray var. meionandrum (Koehne) Trel.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (129, 'Cylindropuntia acanthocarpa (Engelm. & J.M. Bigelow)');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (130, 'Centratherum Cass.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (131, 'Byssoloma subdiscordans (Nyl.) P. James');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (132, 'Ephedra ×arenicola Cutler');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (133, 'Puccinellia phryganodes (Trin.) Scribn. & Merr.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (134, 'Cyperus fugax Liebm.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (135, 'Tropaeolum tuberosum Ruiz & Pav.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (136, 'Silene involucrata (Cham. & Schltdl.) Bocquet ssp. elatior (Regel) Bocquet');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (137, 'Pterocarpus osun Craib');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (138, 'Erigeron biolettii Greene');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (139, 'Sicyosperma A. Gray');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (140, 'Calylophus hartwegii (Benth.) P.H. Raven ssp. hartwegii');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (141, 'Verbena neomexicana (A. Gray) Small');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (142, 'Rinodina archaea (Ach.) Arnold');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (143, 'Aristida palustris (Chapm.) Vasey');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (144, 'Pyrenula cuyabensis (Malme) R.C. Harris');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (145, 'Plantago major L.');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (146, 'Lathrocasis tenerrima (A. Gray) L.A. Johnson');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (147, 'Rhizocarpon anseris Lynge');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (148, 'Aspicilia perradiata (Nyl.) Hue');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (149, 'Lupinus concinnus J. Agardh ssp. orcuttii (S. Watson) D. Dunn');
insert into Diagnosis (diagnosis_id, diagnosis_name) values (150, 'Sisyrinchium idahoense E.P. Bicknell var. idahoense');
