insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (1, 'Smederevska Palanka', '819 Acker Point', 'Camido');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (2, 'Tours', '85 Atwood Crossing', 'Quire');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (3, 'Agua Buena', '637 Sachs Road', 'Rhynyx');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (4, 'Phatthalung', '01 Brentwood Drive', 'Skippad');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (5, 'Qingyang', '258 Center Drive', 'Kazio');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (6, 'Staryy Krym', '1792 Steensland Junction', 'Demizz');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (7, 'Zográfos', '1 Rutledge Park', 'Wikibox');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (8, 'Gondar', '30604 Hanson Drive', 'Skinte');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (9, 'Gamleby', '4922 Petterle Road', 'Kamba');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (10, 'Byala Slatina', '7 Nevada Point', 'Blogpad');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (11, 'Purbalingga', '9 Sullivan Street', 'Yadel');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (12, 'Bar', '1 Oriole Road', 'Linkbridge');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (13, 'Yarmolyntsi', '536 Coolidge Road', 'Fadeo');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (14, 'Benchu', '252 Grasskamp Trail', 'Digitube');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (15, 'Fengqiao', '11827 Di Loreto Street', 'Chatterpoint');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (16, 'Söderhamn', '1283 Armistice Hill', 'Zoomdog');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (17, 'Babakan Baru', '80 Chive Place', 'Rhynoodle');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (18, 'Sísion', '3 Orin Road', 'Dynazzy');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (19, 'Pniewy', '58 Kim Junction', 'Oyondu');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (20, 'Kinalansan', '70 Canary Plaza', 'Aivee');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (21, 'Huangfang', '4738 Dakota Alley', 'Livetube');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (22, 'Paris La Défense', '26124 Ronald Regan Road', 'Rooxo');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (23, 'Pô', '22953 Manufacturers Crossing', 'Dynazzy');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (24, 'Kuntong', '71521 Arkansas Place', 'Zoombeat');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (25, 'Caaguazú', '65292 Ilene Circle', 'Skimia');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (26, 'Shimen', '96 Dwight Drive', 'Jaxnation');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (27, 'Bilaran', '243 Miller Road', 'Feedbug');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (28, 'Punaauia', '9231 Sage Place', 'Oozz');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (29, 'Taivalkoski', '7509 Raven Hill', 'Yamia');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (30, 'Héroumbili', '3660 Sunbrook Terrace', 'Jaxnation');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (31, 'Grand Junction', '8 Laurel Parkway', 'Topicstorm');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (32, 'Ankou', '8778 Clemons Crossing', 'Rooxo');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (33, 'Wabana', '3543 Charing Cross Parkway', 'Thoughtbridge');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (34, 'Sedlice', '1 Glendale Point', 'Topicstorm');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (35, 'New York City', '9 Starling Crossing', 'Plambee');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (36, 'Luxi', '382 Birchwood Drive', 'Voonyx');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (37, 'Pingshan', '4 Trailsway Place', 'Flipopia');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (38, 'Phra Khanong', '5643 Anhalt Trail', 'Dynava');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (39, 'Angoulême', '841 Di Loreto Pass', 'Pixoboo');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (40, 'Thala', '05217 Porter Crossing', 'Viva');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (41, 'Daminggong', '0 Old Gate Way', 'Eidel');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (42, 'Jishan', '5 Sachtjen Way', 'Twitterworks');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (43, 'Chenfang', '86621 Haas Park', 'Divavu');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (44, 'Campor', '2456 Westport Center', 'Divanoodle');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (45, 'Wanganui', '31456 Southridge Way', 'Zoomzone');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (46, 'Novomoskovsk', '039 Ludington Pass', 'Camimbo');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (47, 'Dordrecht', '79 Pond Street', 'Bubbletube');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (48, 'Chinandega', '8884 Dovetail Circle', 'Flipstorm');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (49, 'Białaczów', '340 3rd Lane', 'Vitz');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (50, 'Tetebatu', '12 Vahlen Park', 'Einti');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (51, 'Dimiao', '9096 Katie Center', 'Thoughtsphere');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (52, 'Magdaleno Aguilar', '4 Barby Pass', 'Realbuzz');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (53, 'Maiyema', '07 Blaine Lane', 'Wikizz');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (54, 'Sanban', '8785 Kings Road', 'Lajo');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (55, 'Santo Niño', '8 Center Plaza', 'Brainsphere');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (56, 'Bromma', '5474 Bayside Avenue', 'Abata');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (57, 'Rio de Moinhos', '38303 Cascade Crossing', 'Browsetype');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (58, 'Poniatowa', '7 7th Junction', 'Centizu');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (59, 'Gemena', '12 Golden Leaf Junction', 'Rooxo');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (60, 'Kapsabet', '8 Stoughton Drive', 'Topdrive');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (61, 'Rakičan', '3342 Hazelcrest Circle', 'Meezzy');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (62, 'Mori', '9335 Lindbergh Plaza', 'Edgeblab');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (63, 'Yanghu', '649 Farmco Street', 'Eare');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (64, 'Kašina', '08 Fulton Terrace', 'Gabcube');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (65, 'Gilowice', '65 Main Pass', 'Trilith');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (66, 'Pampierstad', '9 Maryland Alley', 'Kazu');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (67, 'Saint-Dié-des-Vosges', '157 Stoughton Alley', 'Youspan');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (68, 'Sandnes', '9 Evergreen Court', 'Shufflebeat');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (69, 'Jatibonico', '3 Pennsylvania Lane', 'Zooxo');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (70, 'Luhyny', '248 Springs Avenue', 'Quatz');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (71, 'Huatan', '5 Delladonna Point', 'Mymm');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (72, 'Nykvarn', '01 Talmadge Plaza', 'Lazzy');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (73, 'Sucre', '5 Farmco Drive', 'Fivechat');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (74, 'Catungawan Sur', '10 Kennedy Court', 'Ntags');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (75, 'Paya Dapur', '27 Harbort Lane', 'Dablist');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (76, 'Ciénaga', '87 Oak Valley Court', 'Brainsphere');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (77, 'Ústí nad Labem', '52 Oriole Plaza', 'Ntag');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (78, 'Langxi', '917 Northwestern Court', 'Tambee');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (79, 'Jinquan', '64100 Northview Lane', 'Edgeify');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (80, 'Xianglan', '51649 Sheridan Circle', 'Vipe');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (81, 'Tiblawan', '5 Pleasure Point', 'Divape');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (82, 'Sedayulawas', '362 Hollow Ridge Plaza', 'Oloo');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (83, 'Vinica', '53 Prentice Place', 'Devshare');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (84, 'Shuanglu', '1683 East Avenue', 'Buzzdog');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (85, 'Miętne', '2708 Orin Terrace', 'Devpoint');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (86, 'Colquechaca', '38869 Dixon Lane', 'Zoomcast');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (87, 'Ang Thong', '09555 Farwell Parkway', 'Yata');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (88, 'Lyon', '21480 Golf Lane', 'Camido');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (89, 'Shangxian', '608 Vermont Way', 'Twimbo');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (90, 'Mosteiro', '537 Gulseth Parkway', 'Feedbug');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (91, 'Glinka', '96371 Spohn Court', 'Kayveo');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (92, 'Dimiao', '7 Dwight Alley', 'Mynte');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (93, 'Radzanów', '6912 Waubesa Hill', 'Blogpad');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (94, 'Bealanana', '10100 Reindahl Place', 'Wikizz');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (95, 'Houston', '0735 Elgar Way', 'Eadel');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (96, 'Fayaoué', '4535 Southridge Trail', 'Browsetype');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (97, 'Piraí', '7928 Rockefeller Avenue', 'Fivespan');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (98, 'Hangzhou', '41914 Springs Way', 'Twitternation');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (99, 'Cantapoy', '08 Debra Way', 'Zoombeat');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (100, 'Arauco', '50745 Charing Cross Plaza', 'Meemm');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (101, 'Xincheng', '6786 Fulton Center', 'Browsebug');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (102, 'Belén de Umbría', '07907 Springview Circle', 'Realcube');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (103, 'Kadubincarung', '802 Harbort Crossing', 'Gabvine');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (104, 'Ängelholm', '655 Kipling Crossing', 'Kwinu');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (105, 'Pedreira', '8749 Hanson Plaza', 'Skiba');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (106, 'Karangpawitan', '394 Coolidge Avenue', 'Twinder');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (107, 'Veles', '9897 Sommers Crossing', 'Lazz');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (108, 'Kabuynan', '9 Lotheville Point', 'InnoZ');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (109, 'Solomenskoye', '720 Sachs Parkway', 'Jayo');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (110, 'Camajuaní', '353 Magdeline Crossing', 'Skiba');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (111, 'Lewograran', '7081 Schiller Point', 'Tazzy');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (112, 'Otun', '08415 Kensington Point', 'Jetwire');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (113, 'Simabur', '52209 Kenwood Road', 'Shufflester');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (114, 'La Quiaca', '546 Talisman Way', 'Tagopia');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (115, 'Xiaoguai', '6376 Ilene Center', 'Mita');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (116, 'Mirabel', '7220 Oakridge Crossing', 'Feedmix');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (117, 'Paipa', '08 Luster Trail', 'Flashset');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (118, 'Huacheng', '88 Meadow Ridge Circle', 'Trupe');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (119, 'Rust’avi', '93 Carberry Crossing', 'Devpoint');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (120, 'Zuocun', '34 Browning Lane', 'Feedbug');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (121, 'Yanqul', '800 Northview Parkway', 'Zoonder');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (122, 'Karanganyar', '05 Waubesa Plaza', 'Wordify');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (123, 'Babica', '8 Claremont Park', 'Gabtype');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (124, 'Huangqiao', '5 Trailsway Street', 'Babbleopia');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (125, 'Karakul’', '8 Lotheville Crossing', 'Jamia');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (126, 'Tanabi', '3 Orin Crossing', 'BlogXS');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (127, 'Makuyuni', '00694 2nd Crossing', 'Latz');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (128, 'Banjar Danginsema', '5332 Bunker Hill Junction', 'Skimia');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (129, 'Verkhniy Avzyan', '7 Quincy Parkway', 'Yodoo');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (130, 'Cláudio', '280 Southridge Avenue', 'Lajo');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (131, 'Mwaya', '07274 Fallview Terrace', 'Ntag');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (132, 'Sendangkemulian', '568 Westridge Crossing', 'Aibox');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (133, 'Photharam', '46137 Shasta Center', 'Rhycero');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (134, 'La Tour-du-Pin', '881 Rusk Alley', 'Jaxnation');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (135, 'Wangjiang', '67 Lakewood Park', 'Pixope');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (136, 'Jiangqiao', '92969 Thompson Circle', 'Mydeo');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (137, 'Trucuk', '5133 Arapahoe Point', 'Quimm');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (138, 'Khal’ch', '1534 Emmet Park', 'Devshare');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (139, 'Bahía Blanca', '9495 Moulton Park', 'Tagtune');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (140, 'Lemahputih', '25 International Park', 'Kwimbee');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (141, 'Qesarya', '69609 Brentwood Alley', 'Dabshots');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (142, 'Dafang', '7 Karstens Street', 'Plambee');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (143, 'Longshan', '89 Vahlen Road', 'Youspan');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (144, 'Punkalaidun', '0202 Elmside Street', 'Brainbox');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (145, 'Acandí', '61819 Prentice Trail', 'Camimbo');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (146, 'Chuarrancho', '8642 International Court', 'Babbleopia');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (147, 'Chengjiao', '3 Nelson Street', 'Gigaclub');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (148, 'Nemuro', '4903 Stoughton Court', 'Aimbu');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (149, 'Astana', '221 Crescent Oaks Junction', 'Youfeed');
insert into Hospital (hospital_id, hospital_city, hospital_address, hospital_name) values (150, 'Grammatikó', '16 Burrows Pass', 'Oba');
