insert into Procedure (procedure_id, procedure_name) values (1, 'Hill Cane');
insert into Procedure (procedure_id, procedure_name) values (2, 'Cymophora');
insert into Procedure (procedure_id, procedure_name) values (3, 'Fremont County Rockcress');
insert into Procedure (procedure_id, procedure_name) values (4, 'Soldier Rockcress');
insert into Procedure (procedure_id, procedure_name) values (5, 'Roundleaf Orchid');
insert into Procedure (procedure_id, procedure_name) values (6, 'Arkansas River Feverfew');
insert into Procedure (procedure_id, procedure_name) values (7, 'Splitleaf Cyanea');
insert into Procedure (procedure_id, procedure_name) values (8, 'Rinodina Lichen');
insert into Procedure (procedure_id, procedure_name) values (9, 'Devil''s-pepper');
insert into Procedure (procedure_id, procedure_name) values (10, 'Lorent''s Goatgrass');
insert into Procedure (procedure_id, procedure_name) values (11, 'Paiute Buckwheat');
insert into Procedure (procedure_id, procedure_name) values (12, 'Scaleleaf False Foxglove');
insert into Procedure (procedure_id, procedure_name) values (13, 'Dot Lichen');
insert into Procedure (procedure_id, procedure_name) values (14, 'Stink Currant');
insert into Procedure (procedure_id, procedure_name) values (15, 'Bigleaf Snowbell');
insert into Procedure (procedure_id, procedure_name) values (16, 'Silver-dollar Eucalyptus');
insert into Procedure (procedure_id, procedure_name) values (17, 'Coastal Beaksedge');
insert into Procedure (procedure_id, procedure_name) values (18, 'Spiny Holdback');
insert into Procedure (procedure_id, procedure_name) values (19, 'Smooth Oxeye');
insert into Procedure (procedure_id, procedure_name) values (20, 'Bischoff''s Rinodina Lichen');
insert into Procedure (procedure_id, procedure_name) values (21, 'Huachuca Mountain Indian Paintbrush');
insert into Procedure (procedure_id, procedure_name) values (22, 'Tumamoc Globeberry');
insert into Procedure (procedure_id, procedure_name) values (23, 'Bald Mountain Milkvetch');
insert into Procedure (procedure_id, procedure_name) values (24, 'Saururus');
insert into Procedure (procedure_id, procedure_name) values (25, 'Giant Shield Lichen');
insert into Procedure (procedure_id, procedure_name) values (26, 'San Joaquin Snakeweed');
insert into Procedure (procedure_id, procedure_name) values (27, 'Marsh-elder');
insert into Procedure (procedure_id, procedure_name) values (28, 'Wood Saxifrage');
insert into Procedure (procedure_id, procedure_name) values (29, 'Japanese Ulota Moss');
insert into Procedure (procedure_id, procedure_name) values (30, 'Spiny Kidneywood');
insert into Procedure (procedure_id, procedure_name) values (31, 'Korean Hornbeam');
insert into Procedure (procedure_id, procedure_name) values (32, 'Violet Snapdragon');
insert into Procedure (procedure_id, procedure_name) values (33, 'Lesson''s Cyrtandra');
insert into Procedure (procedure_id, procedure_name) values (34, 'Frosted Cyrtandra');
insert into Procedure (procedure_id, procedure_name) values (35, 'Turkeypeas');
insert into Procedure (procedure_id, procedure_name) values (36, 'Heartleaf Noseburn');
insert into Procedure (procedure_id, procedure_name) values (37, 'Common Barley');
insert into Procedure (procedure_id, procedure_name) values (38, 'Roundleaf Waterlily');
insert into Procedure (procedure_id, procedure_name) values (39, 'Winter Creeper');
insert into Procedure (procedure_id, procedure_name) values (40, 'Cabbage');
insert into Procedure (procedure_id, procedure_name) values (41, 'Brake Fern');
insert into Procedure (procedure_id, procedure_name) values (42, 'Dewflower');
insert into Procedure (procedure_id, procedure_name) values (43, 'Texas Madeiravine');
insert into Procedure (procedure_id, procedure_name) values (44, 'Ibex Buckwheat');
insert into Procedure (procedure_id, procedure_name) values (45, 'Dwarf Fireweed');
insert into Procedure (procedure_id, procedure_name) values (46, 'Menzies'' Goldenbush');
insert into Procedure (procedure_id, procedure_name) values (47, 'Polished Blazingstar');
insert into Procedure (procedure_id, procedure_name) values (48, 'Cineraria');
insert into Procedure (procedure_id, procedure_name) values (49, 'Artist''s Popcornflower');
insert into Procedure (procedure_id, procedure_name) values (50, 'Sedge');
insert into Procedure (procedure_id, procedure_name) values (51, 'Pineland Nailwort');
insert into Procedure (procedure_id, procedure_name) values (52, 'Simple Campion');
insert into Procedure (procedure_id, procedure_name) values (53, 'Sunset Lupine');
insert into Procedure (procedure_id, procedure_name) values (54, 'Eightpetal Mountain-avens');
insert into Procedure (procedure_id, procedure_name) values (55, 'Ditch Rabbitsfoot Grass');
insert into Procedure (procedure_id, procedure_name) values (56, 'Texas Croton');
insert into Procedure (procedure_id, procedure_name) values (57, 'Hillebrand''s Flatsedge');
insert into Procedure (procedure_id, procedure_name) values (58, 'Diehl''s Milkvetch');
insert into Procedure (procedure_id, procedure_name) values (59, 'Wallowa Cryptantha');
insert into Procedure (procedure_id, procedure_name) values (60, 'Mckittrick''s Solomon''s Seal');
insert into Procedure (procedure_id, procedure_name) values (61, 'Common Woolly Sunflower');
insert into Procedure (procedure_id, procedure_name) values (62, 'Nevin''s Barberry');
insert into Procedure (procedure_id, procedure_name) values (63, 'Mottled Tuberose');
insert into Procedure (procedure_id, procedure_name) values (64, 'Plummer''s Candyleaf');
insert into Procedure (procedure_id, procedure_name) values (65, 'Thickleaf Phlox');
insert into Procedure (procedure_id, procedure_name) values (66, 'Western White Pine');
insert into Procedure (procedure_id, procedure_name) values (67, 'Longleaf Camphorweed');
insert into Procedure (procedure_id, procedure_name) values (68, 'Hawai''i Delissea');
insert into Procedure (procedure_id, procedure_name) values (69, 'Carolina Leaf-flower');
insert into Procedure (procedure_id, procedure_name) values (70, 'Navelwort');
insert into Procedure (procedure_id, procedure_name) values (71, 'Rockwort');
insert into Procedure (procedure_id, procedure_name) values (72, 'Fleshyfruit Gladecress');
insert into Procedure (procedure_id, procedure_name) values (73, 'Scabland Penstemon');
insert into Procedure (procedure_id, procedure_name) values (74, 'Makou');
insert into Procedure (procedure_id, procedure_name) values (75, 'Peru Roccella Lichen');
insert into Procedure (procedure_id, procedure_name) values (76, 'Bradley''s Spleenwort');
insert into Procedure (procedure_id, procedure_name) values (77, 'Balsam Bird''s-foot Trefoil');
insert into Procedure (procedure_id, procedure_name) values (78, 'Menzies'' Larkspur');
insert into Procedure (procedure_id, procedure_name) values (79, 'Pribilof Dwarf Gentian');
insert into Procedure (procedure_id, procedure_name) values (80, 'Lacy Tansyaster');
insert into Procedure (procedure_id, procedure_name) values (81, 'Hawkweed Oxtongue');
insert into Procedure (procedure_id, procedure_name) values (82, 'Island Chinchweed');
insert into Procedure (procedure_id, procedure_name) values (83, 'Shaddock');
insert into Procedure (procedure_id, procedure_name) values (84, 'Wand Blazing Star');
insert into Procedure (procedure_id, procedure_name) values (85, 'Altai Fescue');
insert into Procedure (procedure_id, procedure_name) values (86, 'Hall''s Suncup');
insert into Procedure (procedure_id, procedure_name) values (87, 'Tricolor Daisy');
insert into Procedure (procedure_id, procedure_name) values (88, 'Hawai''i Woodrush');
insert into Procedure (procedure_id, procedure_name) values (89, 'Jacana');
insert into Procedure (procedure_id, procedure_name) values (90, 'Chilean Needlegrass');
insert into Procedure (procedure_id, procedure_name) values (91, 'Texas Quillwort');
insert into Procedure (procedure_id, procedure_name) values (92, 'African Plume');
insert into Procedure (procedure_id, procedure_name) values (93, 'Ash Meadows Gumweed');
insert into Procedure (procedure_id, procedure_name) values (94, 'One And A Half Flower Reedgrass');
insert into Procedure (procedure_id, procedure_name) values (95, 'Slender Wheatgrass');
insert into Procedure (procedure_id, procedure_name) values (96, 'Siala');
insert into Procedure (procedure_id, procedure_name) values (97, 'Northern Rimmed Lichen');
insert into Procedure (procedure_id, procedure_name) values (98, 'Heartleaf Saxifrage');
insert into Procedure (procedure_id, procedure_name) values (99, 'Billarder''s Bryum Moss');
insert into Procedure (procedure_id, procedure_name) values (100, 'Spring Biatora Lichen');
insert into Procedure (procedure_id, procedure_name) values (101, 'Brittlestem');
insert into Procedure (procedure_id, procedure_name) values (102, 'Sticky Oxeye');
insert into Procedure (procedure_id, procedure_name) values (103, 'River Teatree');
insert into Procedure (procedure_id, procedure_name) values (104, 'Carolina Springbeauty');
insert into Procedure (procedure_id, procedure_name) values (105, 'Rattlesnake Brome');
insert into Procedure (procedure_id, procedure_name) values (106, 'Redclay Hawthorn');
insert into Procedure (procedure_id, procedure_name) values (107, 'Hood River Milkvetch');
insert into Procedure (procedure_id, procedure_name) values (108, 'Shortlobe Penstemon');
insert into Procedure (procedure_id, procedure_name) values (109, 'Orthotrichum Moss');
insert into Procedure (procedure_id, procedure_name) values (110, 'Summergrass');
insert into Procedure (procedure_id, procedure_name) values (111, 'Foothill Gilia');
insert into Procedure (procedure_id, procedure_name) values (112, 'Hen And Chickens');
insert into Procedure (procedure_id, procedure_name) values (113, 'Piedmont Threeawn');
insert into Procedure (procedure_id, procedure_name) values (114, 'Mormon Tea');
insert into Procedure (procedure_id, procedure_name) values (115, 'Yellow ‘ilima');
insert into Procedure (procedure_id, procedure_name) values (116, 'Water Wattle');
insert into Procedure (procedure_id, procedure_name) values (117, 'Matted Lichen');
insert into Procedure (procedure_id, procedure_name) values (118, 'Wild Hydrangea');
insert into Procedure (procedure_id, procedure_name) values (119, 'Cassine');
insert into Procedure (procedure_id, procedure_name) values (120, 'Hawai''i Silversword');
insert into Procedure (procedure_id, procedure_name) values (121, 'La Plata Sandspurry');
insert into Procedure (procedure_id, procedure_name) values (122, 'Roundleaf Goldenrod');
insert into Procedure (procedure_id, procedure_name) values (123, 'Buckwheat Milkvetch');
insert into Procedure (procedure_id, procedure_name) values (124, 'Longleaf Spiderwort');
insert into Procedure (procedure_id, procedure_name) values (125, 'Mat Penstemon');
insert into Procedure (procedure_id, procedure_name) values (126, 'Schott''s Wirelettuce');
insert into Procedure (procedure_id, procedure_name) values (127, 'False Foxglove');
insert into Procedure (procedure_id, procedure_name) values (128, 'Rinodina Lichen');
insert into Procedure (procedure_id, procedure_name) values (129, 'Overcup Oak');
insert into Procedure (procedure_id, procedure_name) values (130, 'Artist''s Popcornflower');
insert into Procedure (procedure_id, procedure_name) values (131, 'Hartz''s Bluegrass');
insert into Procedure (procedure_id, procedure_name) values (132, 'Savanna Blazing Star');
insert into Procedure (procedure_id, procedure_name) values (133, 'Dwarf Spleenwort');
insert into Procedure (procedure_id, procedure_name) values (134, 'Mediterranean Crownvetch');
insert into Procedure (procedure_id, procedure_name) values (135, 'Falsegold Groundsel');
insert into Procedure (procedure_id, procedure_name) values (136, 'Shepherdsneedle');
insert into Procedure (procedure_id, procedure_name) values (137, 'Alani Wai');
insert into Procedure (procedure_id, procedure_name) values (138, 'Nelson''s Brachythecium Moss');
insert into Procedure (procedure_id, procedure_name) values (139, 'Bonnet Orchid');
insert into Procedure (procedure_id, procedure_name) values (140, 'Sour Pricklypear');
insert into Procedure (procedure_id, procedure_name) values (141, 'Australian Lovegrass');
insert into Procedure (procedure_id, procedure_name) values (142, 'Mormon Tea');
insert into Procedure (procedure_id, procedure_name) values (143, 'Leatherweed');
insert into Procedure (procedure_id, procedure_name) values (144, 'Greenflowered Wintergreen');
insert into Procedure (procedure_id, procedure_name) values (145, 'Threadleaf Phacelia');
insert into Procedure (procedure_id, procedure_name) values (146, 'Rim Lichen');
insert into Procedure (procedure_id, procedure_name) values (147, 'Paralejo De Monte');
insert into Procedure (procedure_id, procedure_name) values (148, 'Prickly Hawkweed');
insert into Procedure (procedure_id, procedure_name) values (149, 'Eranthemum');
insert into Procedure (procedure_id, procedure_name) values (150, 'Black Ironbox');
